### PR TITLE
Fix slugging when nesting accordions.

### PR DESCRIPTION
**Pull request by megatronCGN**
The `wfaccordionGroup`-constructer selects all children `js-accordion` elements to build its accordions. This leads to a bug in the slugging mechanism, when accordions are nested. In the generation of the outermost `accordionGroup`, the `triggerElement` has already been cleaned of attributes so when the inner `accordionGroup` is generated, the slugging defaults to building the slug from the trigger-content, because there is no `id`-attribute anymore to generate the slug from. This PR fixes this bug by filtering the selected  `js-accordion`-elements to direct children of the `accordionGroup`.

### CODE REVIEW

**Review by polarbirke — APPROVED** [review]
Sounds plausible 👍

**Comment by megatronCGN** [comment]
@polarbirke do you think we should adjust the hashtag logic to deal with nested accordions as well?

**Comment by polarbirke** [comment]
> do you think we should adjust the hashtag logic to deal with nested accordions as well?

@megatronCGN Oh, good point. Hm. That's going to be tricky… we'd have to somehow expose parent accordion IDs to nested accordions, so a deeplink to a nested accordion can open both the parent and the nested child. 🤔 

I'd be tempted to say "yes, we should", but how big do you estimate the effort?

**Comment by megatronCGN** [comment]
@polarbirke I am thinking about a custom event like `expandedByHashUpdate`, which should hit all accordion-roots while bubbling, when dispatched by the inner accordion. Accordion-roots listen to the event and expand themselves on the events way up.

**Comment by polarbirke** [comment]
Uh, smart! 🙌

**Comment by polarbirke** [comment]
> by **filtering** the selected js-accordion-elements **to direct children** of the accordionGroup.

TIL: Das war ein [breaking change](https://github.com/webfactory/gemeinsamer-bundesausschuss/issues/1587) :sob: Hab ich 2023 nicht gesehen.

**Pull request merged**
